### PR TITLE
register page added

### PR DESCRIPTION
**Pull request by ahmad2shadab**
created *register page* and added to  `feature/register/shadab`

### CODE REVIEW

**Review by hadissulejmani — CHANGES_REQUESTED** [review]
When I try to run /register route, it is obviously giving me some errors, please consider to recognize the difference between Client components and Server components, and resolve the issues!
Screenshot 2024-03-20 at 17 03 51

**Comment by ahmad2shadab** [comment]
Screenshot (8)

**Comment by ahmad2shadab** [comment]
Screenshot (10)

**Review by hadissulejmani — APPROVED** [review]
You have done a great job. Your changes will be merged immediately.

**Comment by ahmad2shadab** [comment]
But why there's an error ?

**Comment by hadissulejmani** [comment]
> But why there's an error ?

I am not seeing any error, can you send the detailed description of the error?

**Comment by ahmad2shadab** [comment]
Screenshot (13)
Screenshot (14)
Screenshot (15)

**Comment by ahmad2shadab** [comment]
> > But why there's an error ?
> 
> I am not seeing any error, can you send the detailed description of the error?

Screenshot (13)
Screenshot (14)
Screenshot (15)

**Pull request merged**
